version: '3.4'

services:
  comp11025sworkspace:
    image: comp11025sworkspace
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 exercises\ex02_wordle.py "]
    ports:
      - 5678:5678
